[package]
name = "gift-wrapping"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.15.1", features = ["dynamic_linking"] }
bevy_prototype_lyon = "0.13.0"
rand = "0.8.5"
